apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: greenstock
  name: cluster-admin-sa 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: cluster-admin-sa
    namespace: greenstock
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io