apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: greenstock
  name: cluster-admin-sa 
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-rolebinding
subjects:
  - kind: ServiceAccount
    name: k8s-tester
    namespace: greenstoc
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io