apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: greenstock
  name: k8s-tester-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: greenstock
  name: greenstock-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-tester-sa-rolebinding
  namespace: k8s-tester
subjects:
  - kind: ServiceAccount
    name: k8s-tester-sa
    namespace: greenstock
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: greenstock-pod-reader